app = "magvox-voxelbox"
primary_region = "sfo"

[build]
command = "npm start"
build_path = "."

[deploy]
restart_policy_type = "never"

[build.nixpacks]
plan = "nodejs"
nodeVersion = "20"

[http]
service_port = 8080
force_https = true